apiVersion: batch/v1
kind: Job
metadata:
  name: iree-benchmark-job

spec:
  template:
    spec:
      volumes:
      - name: iree-benchmark-vol
        persistentVolumeClaim:
          claimName: eric-pvc
      containers:
      - name: iree-benchmark-suite
        image: efric/iree-benchmark-test
        command: ["/bin/bash", "-c"]
        volumeMounts:
        - name: iree-benchmark-vol
          mountPath: /data/shark # for IRPA weights
        - name: iree-benchmark-vol
          mountPath: /iree-cache # for build cache & signatures
        env:
        # Change values for custom build flags
        - name: IREE_CMAKE_FLAGS
          value: >
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
            -DIREE_BUILD_PYTHON_BINDINGS=1
            -DIREE_HAL_DRIVER_HIP=1
            -DIREE_TARGET_BACKEND_ROCM=1
            -DIREE_HIP_TEST_TARGET_CHIP=gfx942
            -DIREE_ENABLE_ASSERTIONS=1
            -DIREE_BUILD_TRACY=0
            -DIREE_ENABLE_COMPILER_TRACING=0
            -DIREE_ENABLE_RUNTIME_TRACING=1
            -DIREE_ENABLE_LLD=1
            -DIREE_ENABLE_SPLIT_DWARF=1
            -DIREE_ENABLE_THIN_ARCHIVES=1
            -DLLVM_INSTALL_UTILS=1
            -DCMAKE_EXPORT_COMPILE_COMMANDS=1
        - name: IREE_GIT_BRANCH
          value: "tags/v3.4.0" # switch out for desired branch
        - name: BENCHMARK_OUT
          value: "/iree-model-benchmark/sdxl/fp8-model/results.json"
        - name: BENCHMARK_OUT_FORMAT
          value: "json"
        - name: HIP_TARGET_CHIP
          value: "gfx942"
        - name: TUNING_CHIP_CONFIG_MODE
          value: "none"
        - name: BATCH_SIZE
          value: "4"
        - name: HIP_DEVICE_ID
          value: "0"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: oci-s3-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: oci-s3-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: oci-s3-credentials
              key: AWS_SESSION_TOKEN
        args:
          - |
            set -eu
            readonly IREE_DIR="/iree"
            readonly BENCHMARK_DIR="/iree-model-benchmark"
            readonly CACHE_ROOT="/iree-cache"

            cd "$BENCHMARK_DIR"
            git pull origin main

            cd "$IREE_DIR"
            git fetch --all --tags
            git checkout "$IREE_GIT_BRANCH"
            #git pull origin "$IREE_GIT_BRANCH"
            git submodule update --init --recursive

            readonly HEAD_COMMIT=$(git rev-parse HEAD)
            readonly CONFIG_HASH=$(echo -n "$HEAD_COMMIT|${IREE_CMAKE_FLAGS//$'\n'/ }" | md5sum | awk '{print $1}')

            readonly BUILD_DIR="${CACHE_ROOT}/build-${CONFIG_HASH}"
            readonly INSTALL_DIR="${CACHE_ROOT}/install-${CONFIG_HASH}"
            readonly SIG_FILE="${CACHE_ROOT}/.signature-${CONFIG_HASH}"
            readonly TMP_SIG="/tmp/current.signature"

            mkdir -p "$CACHE_ROOT"

            echo "$HEAD_COMMIT" > "$TMP_SIG"

            readonly COMMON_FLAGS="-fno-omit-frame-pointer"
            readonly CXX="clang++"
            readonly CC="clang"
   
            # Rebuild if needed
            if ! cmp -s "$TMP_SIG" "$SIG_FILE"; then
              echo "[INFO] Rebuilding IREE for commit $HEAD_COMMIT"
              rm -rf "$BUILD_DIR" "$INSTALL_DIR"
              mkdir -p "$BUILD_DIR"
              cmake "$IREE_DIR" -B "$BUILD_DIR" -GNinja \
                $IREE_CMAKE_FLAGS \
                -DPython3_EXECUTABLE="$(which python)" \
                -DCMAKE_CXX_COMPILER="$CXX" \
                -DCMAKE_C_COMPILER="$CC" \
                -DCMAKE_CXX_FLAGS="${COMMON_FLAGS}" \
                -DCMAKE_C_FLAGS="${COMMON_FLAGS}" \
                -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"

              #echo "[INFO] IREE CMake successfully configured build system in $BUILD_DIR"
              cmake --build "$BUILD_DIR" -j"$(nproc)"
              #echo "[INFO] IREE successfully built in $BUILD_DIR"
              #cmake --install "$BUILD_DIR"
              #echo "[INFO] IREE installed on system."
              cp "$TMP_SIG" "$SIG_FILE"
            else
              echo "[INFO] Reusing cached build at $INSTALL_DIR"
            fi
   
            #export PATH="$INSTALL_DIR/bin:$PATH"
   
            if [ ! -f /data/shark/punet_fp8_weights.irpa ]; then
              echo "[INFO] Model weights not found. Downloading IRPA file..."
              curl -L -o /data/shark/punet_fp8_weights.irpa \
                https://sharkpublic.blob.core.windows.net/sharkpublic/sdxl-scripts-weights/punet_fp8_weights.irpa
              echo "42df7496dc012548e5fc1a198cb1161d  /data/shark/punet_fp8_weights.irpa" | md5sum -c || {
                echo "[ERROR] IRPA checksum verification failed" >&2
                exit 1
              }
            fi

            PATH="$BUILD_DIR"/tools:$PATH "$BENCHMARK_DIR"/sdxl/fp8-model/compile-punet.sh "$HIP_TARGET_CHIP" "$TUNING_CHIP_CONFIG_MODE" "$BATCH_SIZE"

            echo "[INFO] Running IREE model benchmarks"
            PATH="$BUILD_DIR"/tools:$PATH "$BENCHMARK_DIR"/sdxl/fp8-model/benchmark-unet.sh "$HIP_DEVICE_ID" "$BATCH_SIZE"

            echo "[INFO] sdxl fp8 model benchmark completed."
            aws s3 cp "$BENCHMARK_OUT" s3://eric-shark-test/results.json
            echo "To download results: aws s3 cp s3://eric-shark-test/results.json /local/path/to/results/"
        resources:
          limits:
            amd.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 0

